name: build-workflow
on: [push]
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run build
      - run: |
          git config --global user.name 'Paul Holden'
          git config --global user.email 'hulkholden@users.noreply.github.com'
          git add -A
          git diff-index --quiet HEAD || git commit -m 'Automated build'
          git push